name: HendrixTest
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.375
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
