name: HendrixTest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0
  lightness: 0.42958673369139433
  saturation: 0.8317191819660366
  rhythmicContrast: 0.9715068200603127
purpose: []
